# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o Pila.o Llista.o Fitxers.o Partida.o $(RES)
LINKOBJ  = main.o Pila.o Llista.o Fitxers.o Partida.o $(RES)
LIBS =  -L"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/lib" -lalleg  
INCS =  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/include" 
CXXINCS =  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/include/c++/3.4.2/backward"  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/include/c++/3.4.2/mingw32"  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/include/c++/3.4.2"  -I"C:/Users/Marc/Downloads/Dev-Cpp_Allegro_Windows8/Dev-Cpp/MinGW32/include" 
BIN  = Blackjack.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Blackjack.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Blackjack.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

Pila.o: Pila.c
	$(CC) -c Pila.c -o Pila.o $(CFLAGS)

Llista.o: Llista.c
	$(CC) -c Llista.c -o Llista.o $(CFLAGS)

Fitxers.o: Fitxers.c
	$(CC) -c Fitxers.c -o Fitxers.o $(CFLAGS)

Partida.o: Partida.c
	$(CC) -c Partida.c -o Partida.o $(CFLAGS)
